### ISSUE TITLE
Nothing happens after u/d/l/r

### ISSUE THREAD

**Issue by wbazant** [christina-zhou-96/geometry-automata#1]
I was curious and went to check out the project! It ran, but propagating the pattern initially didn't work, and I was seeing this error in the console:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/tkinter/__init__.py", line 1883, in __call__
    return self.func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/tkinter/__init__.py", line 804, in callit
    func(*args)
  File "main.py", line 332, in update_boxes
    box.update()
TypeError: update() missing 1 required positional argument: 'ids'
```

I was later able to run the code off the earlier commit 63ef84d4282 by doing `git checkout HEAD~~~` and it was doing pretty stuff that matches the description in the readme, so I think something has gone wrong during the last few commits.

**Comment by christina-zhou-96** [comment]
HAHAHA, thanks! Yeah I'm in the middle of changing the project so the last working commit isn't the head right now. I should probably fix that. Thanks though for checking it out! I'm glad running it at least is straightforward.

**Comment by christina-zhou-96** [comment]
I think it works now - let me know :)

**Comment by wbazant** [comment]
Works for me too!
